// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "duplicate.default.action": string;
      "bulk.master.item": string;
      "bulk.merge.concurrency": number;
      "duplicate.stats.enable": boolean;
    };
  }
}
